---
- name: get zones and A,CNAME records
  include_vars: "{{ item }}"
  with_items:
  - "zones_all.yml"
  - "zones_std.yml"
  - "zones_rvs.yml"
  - "A.yml"
  - "CNAME.yml"
  tags:
  - bind
  - bind-update

- name: get PTR records
  include_vars: "{{ item.domain }}.yml"
  with_items:
  - "{{ reverse_zones }}"
  tags:
  - bind
  - bind-update

- name: get ansible_dns_new_serial_number of all zones
  myfacts: get_facts=yes domain_names={{ all_zones_list|join(',') }}
  tags:
  - bind
  - bind-update

- name: create zones configuration files
  template: src={{ colo }}/{{ item.file }}.j2 dest=/var/named/{{ item.file }} owner=named group=named mode=0644
  with_items:
  - "{{ standard_zones }}"
  tags:
  - bind
  - bind-update

- name: create reverse zones configuration files
  template: src={{ colo }}/{{ item.file }}.j2 dest=/var/named/{{ item.file }} owner=named group=named mode=0644
  with_items:
  - "{{ reverse_zones }}"
  tags:
  - bind
  - bind-update

- name: relaod rndc service to load new records
  shell: rndc freeze && rndc reload && rndc thaw
  tags:
  - bind
  - bind-update
